### PR TITLE
Use Github Actions instead of Travis

### PR DESCRIPTION
**Pull request by gaborbernat**
@naiquevin Travis seems to not respect our pip installation commands, so moved to the more built-in Github Actions.

### CODE REVIEW

**Comment by gaborbernat** [comment]
The action only becomes active on this repository post merge, however you can see it passing on my fork here https://github.com/gaborbernat/pipdeptree/actions/runs/264661050

**Comment by naiquevin** [comment]
@gaborbernat: Wow! Thanks a lot. Now if you rebase your other PR, github action would run on it right? Can you please rebase?

**Comment by naiquevin** [comment]
@gaborbernat: I missed one thing - Any idea if github actions allow us to pin the virtualenv version? For now it's working but that may change in future.

**Comment by gaborbernat** [comment]
Sure I'll put in a new pr.

**Pull request merged**
