### PR TITLE
WIP: Add support to act as pip plugin

### PR DESCRIPTION
**Pull request by msabramo**
This is an experimental feature to make pipdeptree into a **pip plugin**, which is a new concept that I proposed in https://github.com/pypa/pip/pull/2329

```
[marca@marca-mac2 ~WORKON_HOME]$ mktmpenv
New python executable in tmp-4adc64ecf8c6ac9e/bin/python
Please make sure you remove any previous custom paths from your /Users/marca/.pydistutils.cfg file.
Installing setuptools, pip...done.
This is a temporary environment. It will be deleted when you run 'deactivate'.

[marca@marca-mac2 ~VIRTUAL_ENV]$ pip install https://github.com/msabramo/pip/archive/command_plugins.zip
...
Successfully installed pip-6.1.0.dev0

# Install the pipdeptree plugin
[marca@marca-mac2 ~VIRTUAL_ENV]$ pip install https://github.com/msabramo/pipdeptree/archive/pip_plugin.zip
Collecting https://github.com/msabramo/pipdeptree/archive/pip_plugin.zip
  Downloading https://github.com/msabramo/pipdeptree/archive/pip_plugin.zip
     - 20kB 85kB/s
Requirement already satisfied (use --upgrade to upgrade): pip>=1.4.1 in ./lib/python2.7/site-packages (from pipdeptree==0.4.2)
Installing collected packages: pipdeptree
  Running setup.py install for pipdeptree
    Installing pipdeptree script to /Users/marca/python/virtualenvs/tmp-4adc64ecf8c6ac9e/bin
Successfully installed pipdeptree-0.4.2

[marca@marca-mac2 ~VIRTUAL_ENV]$ pip

Usage:
  pip <command> [options]

Commands:
  ...
  deptree                     Display a dependency tree of the installed python packages

[marca@marca-mac2 ~VIRTUAL_ENV]$ pip deptree --help

Usage:
  pip deptree [options]

Deptree Options:
  -f, --freeze                Print names so as to write freeze files
  -a, --all                   list all deps at top level
  -l, --local-only            If in a virtualenv that has global access donot show globally installed packages
  -w, --nowarn                Inhibit warnings about possibly confusing packages
...

# Just installing a few packages so that the output of `pip deptree` is more interesting...
[marca@marca-mac2 ~VIRTUAL_ENV]$ pip install flask ipython
...

[marca@marca-mac2 ~VIRTUAL_ENV]$ pip deptree
wsgiref==0.1.2
Flask==0.10.1
  - Werkzeug [required: >=0.7, installed: 0.9.6]
  - Jinja2 [required: >=2.4, installed: 2.7.3]
    - MarkupSafe [installed: 0.23]
  - itsdangerous [required: >=0.21, installed: 0.24]
ipython==2.3.1
  - gnureadline [installed: 6.3.3]
wheel==0.24.0
```

Cc: @naiquevin, @therealprologic

Refs: https://github.com/naiquevin/pipdeptree/issues/1

### CODE REVIEW

**Comment by naiquevin** [comment]
Great idea and nice work! I hope it gets merged in pip :+1:

**Comment by prologic** [comment]
Are we there yet? :)

**Comment by szepeviktor** [comment]
@msabramo Could you solve merge conflicts?

**Comment by msabramo** [comment]
https://github.com/pypa/pip/pull/2329 has been closed, but there is a new PR for implementing plugin support in pip: https://github.com/pypa/pip/pull/4146

**Comment by msabramo** [comment]
I don't see pip adding plugin support anytime soon, so I'll close this.

**Pull request closed without merging**
