### PR TITLE
Reverse mode

### PR DESCRIPTION
**Pull request by naiquevin**
Implementation for `--reverse` mode. This is actually an alternate implementation for the first one that was proposed via this PR - https://github.com/naiquevin/pipdeptree/pull/33.

The changes on this branch includes major refactoring of code.

### CODE REVIEW

**Comment by naiquevin** [comment]
Example outputs

```
$ python pipdeptree.py -w
Fabric==1.8.2
  - paramiko [required: >=1.10.0, installed: 1.15.2]
    - ecdsa [required: >=0.11, installed: 0.13]
    - pycrypto [required: >=2.1, installed: 2.6.1]
watchdog==0.6.0
  - PyYAML [required: >=3.09, installed: 3.11]
  - argh [required: >=0.8.1, installed: 0.23.3]
  - pathtools [installed: 0.1.2]
Jinja2==2.7.1
  - markupsafe [installed: 0.18]
pylint==1.0.0
  - logilab-common [required: >=0.53.0, installed: 0.60.0]
  - astroid [required: >=0.24.3, installed: 1.0.0]
    - logilab-common [required: >=0.60.0, installed: 0.60.0]
argparse==1.1
Pygments==1.6
mdx-smartypants==1.5.0
  - Markdown [required: >=2.0, installed: 2.3.1]
  - namedentities [required: ==1.5.2, installed: 1.5.2]
  - guess-language [required: >=0.2, installed: 0.2]
wsgiref==0.1.2
````

```
$ python pipdeptree.py -wr
pycrypto==2.6.1
  - paramiko==1.15.2 [requires: pycrypto>=2.1]
    - Fabric==1.8.2 [requires: paramiko]
Markdown==2.3.1
  - mdx-smartypants==1.5.0 [requires: Markdown>=2.0]
markupsafe==0.18
  - Jinja2==2.7.1 [requires: markupsafe]
PyYAML==3.11
  - watchdog==0.6.0 [requires: PyYAML>=3.09]
Pygments==1.6
argparse==1.1
wsgiref==0.1.2
argh==0.23.3
  - watchdog==0.6.0 [requires: argh>=0.8.1]
logilab-common==0.60.0
  - astroid==1.0.0 [requires: logilab-common>=0.53.0]
    - pylint==1.0.0 [requires: astroid]
logilab-common==0.60.0
  - astroid==1.0.0 [requires: logilab-common>=0.60.0]
    - pylint==1.0.0 [requires: astroid]
namedentities==1.5.2
  - mdx-smartypants==1.5.0 [requires: namedentities==1.5.2]
guess-language==0.2
  - mdx-smartypants==1.5.0 [requires: guess-language>=0.2]
pathtools==0.1.2
  - watchdog==0.6.0 [requires: pathtools]
ecdsa==0.13
  - paramiko==1.15.2 [requires: ecdsa>=0.11]
    - Fabric==1.8.2 [requires: paramiko]
```

**Comment by tommilligan** [comment]
Like your approach; now refactored the code is much easier to follow. Good work :+1:

**Comment by naiquevin** [comment]
Thanks. I'll merge my changes into master then and release a new version on PyPI by the end of this week. I really appreciate your PR and all the effort that you put in. It really helped me with my refactoring. Thanks again :-)

**Comment by tommilligan** [comment]
No problem! It was an interesting problem to look at, and a useful tool to use. Also helped me learn a few things along the way

**Pull request merged**
