### PR TITLE
Add command line flag `--json-tree` (#86)

### PR DESCRIPTION
**Pull request by haikoschol**
This changes adds a flag for producing JSON that is nested the same way as the plain text output.

### CODE REVIEW

**Comment by haikoschol** [comment]
CI fails because Travis upgraded PostgreSQL to 10.1. Should work after https://github.com/naiquevin/pipdeptree/pull/90 has been merged.

**Comment by naiquevin** [comment]
Great stuff! Will review and merge in a couple of days along with the other PR. Thanks for picking this up :-)

**Comment by naiquevin** [comment]
LGTM. I've merged your other PR for fixing the build. Can you please rebase?

**Comment by haikoschol** [comment]
Sure. Will take a moment since I'm on vacation without a laptop until March 5th. Will rebase when I'm back.

**Comment by naiquevin** [comment]
Thanks!

**Pull request merged**
